### ISSUE TITLE
ARM config.log error

### ISSUE THREAD

**Issue by bilalin** [neoncoin-tech/xpi-cpuminer#1]
root@localhost:~/xpi-cpuminer# ./configure CFLAGS="-O3 -mfpu=neon" CXXFLAGS="-O3 -mfpu=neon"
checking build system type... aarch64-unknown-linux-gnu                                         checking host system type... aarch64-unknown-linux-gnu                                          checking target system type... aarch64-unknown-linux-gnu                                        checking for a BSD-compatible install... /usr/bin/install -c                                    checking whether build environment is sane... yes                                               checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no                                                                         checking for mawk... mawk                                                                       checking whether make sets $(MAKE)... yes                                                       checking whether make supports nested variables... yes                                          checking whether to enable maintainer-specific portions of Makefiles... no                      checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc                                                                         checking whether the C compiler works... no                                                     configure: error: in `/root/xpi-cpuminer':                                                      configure: error: C compiler cannot create executables                                          See `config.log' for more details

**Comment by neoncoin-project** [comment]
first, the coin and the miner isnt ready yet. and second, its a issue with your compile, try reinstall gcc and g++. Please not compile anything yet. Try : `sudo apt install libc6-dev`

**Comment by neoncoin-project** [comment]
i was able to reproduce your error, you are adding `-mfpu=neon` in a no-ARM machine. Try do `./configure CFLAGS="-O3" CXXFLAGS="-O3"`
